Runtime/Receipt rewrite
nearprotocol/nomicon pull request #13
Opened 2019-12-05 16:08 UTC by fckt

Another iteration to make sure that the explanation is good enough.

2019-12-05 16:35 UTC, fckt commented on docs/BlockchainLayerVsRuntimeLayer.html
> +<li>Communication -- the runtime don't know anything about the current network topology. Receipt has only a receiver_id (a recipient account), but knows nothing about the destination shard, so it's a
rephrased a bit, to make it more explicit here.

2019-12-05 19:43 UTC, maxzaver approved these changes

2019-12-05 19:44 UTC, maxzaver requested changes
Don't delete CNAME it is needed to make sure https://nomicon.io/ points to the website correctly.

2019-12-09 16:32 UTC, maxzaver approved these changes

2019-12-09 17:01 UTC, merged